accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('post', views.PostsListsView.as_view(), name='post_list'),
    path('post-detail/<int:pk>/', views.PostsDetailView.as_view(), name='post_detail'),
    path('post-new/', views.CreateNewPost.as_view(), name='post_new'),
    path('post-edit/<int:pk>/', views.UpdatePost.as_view(), name='post_edit'),
    path('post-delete/<int:pk>/', views.DeletePost.as_view(), name='post_delete'),
    path('', views.HomePage.as_view(), name='home_page'),
    path('about/', views.AboutPage.as_view(), name='about_page'),
    path('result/', views.SearchView.as_view(), name='post_search'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveSmallIntegerField(null=True)
    phone_number = models.CharField(max_length=16, null=True)

pages/models.py
from PIL.Image import Image
from PIL import Image
from django.conf import settings
from django.db import models
from django.urls import reverse


class CustomManager(models.Manager):

     def published(self):

         return self.filter(is_publish=True)


class Posts(models.Model):

    title = models.CharField(max_length=100)
    text = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default='')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='', default='default.jpg', help_text="Post Picture")
    is_publish = models.BooleanField(default=False)
    slug = models.SlugField(default='')

    objects = CustomManager()

    def save(self):
        
        super().save()

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            new_img = (300, 300)
            img.thumbnail(new_img)
            img.save(self.image.path)


    def __str__(self):
        
        return self.title

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'
        ordering = ['-updated', '-created']
        
    def get_absolute_url(self):
        
        return reverse("post_detail", kwargs={"pk": self.pk})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ("username", "email", "phone_number", "age")


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ("username", "email", "phone_number")

pages/forms.py
from django import forms
from .models import Posts


class PostForm(forms.ModelForm):
    slug = forms.SlugField(required=False)

    class Meta:
        model = Posts
        fields = '__all__'
        exclude = ['author']

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'registration/signup.html'

pages/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import (TemplateView,
                                  ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView,
                                  )

from django.urls import reverse_lazy
from .models import Posts
from .forms import PostForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin


class DeletePost(PermissionRequiredMixin, DeleteView):
    permission_required = "pages.delete_post"
    template_name = 'pages/delete_post.html'
    model = Posts
    success_url = reverse_lazy("post_list")
    context_object_name = 'post'


class UpdatePost(PermissionRequiredMixin, UpdateView):
    permission_required = "pages.change_post"
    template_name = 'pages/edit_post.html'
    model = Posts
    form_class = PostForm


class CreateNewPost(LoginRequiredMixin, CreateView):
    template_name = 'pages/post_new.html'
    form_class = PostForm
    model = Posts
    success_url = reverse_lazy('post_list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


'''Optionally can use create_new_post function instead of CreateNewPost class.
For change view you can go to urls.py in this directory and put the function name instead of class name.
Also notice if you use function you should not use .as_view()'''
# @login_required # use this decorator for apply login permission
# def create_new_post(request):
#     if request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             post = form.save(commit=False)
#             post.author = request.user
#             post.save()
#             return redirect('post_list')
#     else:
#         form = PostForm()
#         return render(request, 'pages/post_new.html', context={'form': form})


class PostsDetailView(LoginRequiredMixin, DetailView):
    template_name = 'pages/post_detail.html'
    model = Posts
    context_object_name = 'post'

    def post_detail(request, pk):
        post = get_object_or_404(Posts, pk=pk)
        context = {
            'post': post
        }
        return render(request, 'pages/post_detail.html', context)


'''Optionally can use post_detail function instead of PostDetailView class.
For change view you can go to urls.py in this directory and put the function name instead of class name.
Also notice if you use function you should not use .as_view()'''
# @login_required # use this decorator for apply login permission
# def post_detail(request, pk):
#
#     post = get_object_or_404(Posts, pk=pk)
#     context = {
#         'post': post
#     }
#     return render(request, 'pages/post_detail.html', context)


class PostsListsView(LoginRequiredMixin, ListView):
    template_name = 'pages/Posts.html'
    model = Posts

    def get_queryset(self):
        posts = Posts.objects.filter(is_publish=True)
        return posts


class HomePage(TemplateView):
    template_name = 'pages/index.html'


class AboutPage(TemplateView):
    template_name = 'pages/about.html'


class SearchView(ListView):
    model = Posts
    template_name = 'pages/post_search.html'
    context_object_name = 'all_search_results'

    def get_queryset(self):

        result = super(SearchView, self).get_queryset()
        if query := self.request.GET.get('search'):
            postresult = Posts.objects.filter(Q(title__contains=query) | Q(text__icontains=query))
            result = postresult
        else:
            result = None
        return result

templates/base.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <style>
        .jumbotron{
            padding: 20px;
            margin-bottom: 20px;
            background-color: #e9ecef;
        }
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home_page' %}">HOME</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link " href="{%  url 'about_page'  %}">ABOUT</a>
              <a class="nav-link" href="{%  url 'post_list'  %}">POSTS</a>
              <a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
            </div>
          </div>
        </div>
    </nav>

    {% comment %} <header> {% endcomment %}
        {% comment %} <div class="nav-left">
            <h1><a href="{% url 'home_page' %}">HOME</a></h1>
        </div> {% endcomment %}
        {% comment %} <a href="{%  url 'post_list'  %}">POSTS</a> {% endcomment %}
        {% comment %} <a href="{%  url 'about_page'  %}">ABOUT</a> {% endcomment %}
        {% comment %} <a href="{% url 'admin:index' %}"> admin</a> {% endcomment %}
    {% comment %} </header> {% endcomment %}

{% comment %} {% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else  %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'signup' %}">Sign Up</a>
{% endif %} {% endcomment %}

    <div class = "jumbotron">
        {% block content %}

        {% endblock content %}
    </div>

</body>

templates/pages/Posts.html
{% extends "base.html" %}
{% load humanize %}


{% block content %}
<div style="background-color:white;">
    <h1 style="text-align:center">Posts</h1>
    <a style="text-align:center" class = "btn btn-success" href="{% url 'post_new' %}">+New Blog Post</a>

    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url "post_search" %}" >
        <input style="background-color:lightblue;" class="form-control mr-sm-2" type="search" name="search">
        <button class="btn btn-outline-info my-2 my-sm-0" type="submit"> Search </button>
    </form>
    <hr>


    {% for post in posts_list %}
    <p>
        <a style = "font-size: large" href = "{% url "post_detail" post.pk %}" class="btn btn-dark">{{ post.title }}</a><br>
        <small>created at: {{ post.created | naturaltime}} |</small>
        <small>modified at: {{ post.updated | naturaltime}} |</small>
        <small>author: {{ post.author }}</small>
        <hr>
    </p>
    {% endfor %}
</div>



{% endblock content %}

templates/pages/about.html
{% extends "base.html" %}

{% block content %}

<h1> This is About Page!</h1>

{% endblock content %}

templates/pages/delete_post.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Post</h1>
    <form action = "" method = "post">{% csrf_token %}
        <p>Are you sure you want to delete "{{post.title}}"?</p>
        <input type = "submit" value = "Confirm" class="btn btn-success">
        <a href="{% url 'post_list' %}" class="btn btn-secondary">No</a>
    </form>

{% endblock content %}

templates/pages/edit_post.html
{% extends "base.html" %}

{% block content %}

    <h1>Edit Post</h1>
    <form action = "" method = "post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value = "Save" class="btn btn-success">
    </form>


{% endblock content %}

templates/pages/index.html
{% extends "base.html" %}

{% block content %}

<h1> This is Home Page!</h1>
{% if user.is_authenticated %}
    <div class="alert alert-info" role="alert">
        Hi {{ user.username }}!
    </div>  
    {% comment %} <p>Hi {{ user.username }}!</p> {% endcomment %}
    <p><a href="{% url 'logout' %}" class="btn btn-danger">Log Out</a></p>
{% else  %}
    <div class="alert alert-danger" role="alert">
        You are not logged in!
    </div>
    {% comment %} <p>You are not logged in</p> {% endcomment %}
    <a href="{% url 'login' %}" class="btn btn-success">Log In</a>
    <a href="{% url 'signup' %}" class="btn btn-info">Sign Up</a>
{% endif %}
{% endblock content %}

templates/pages/post_detail.html
{% extends "base.html" %}
{#{% load thumbnail %}#}

{% block content %}

    <h1>{{ post.title }}</h1>
    <img src = '{{post.image.url}}' alt = ''><br>
    <p>{{ post.text }}</p>
    <a href="{% url 'post_edit' post.pk %}" class="btn btn-warning">Edit Post</a>
    <a style="background : red" href="{% url 'post_delete' post.pk %}" class="btn btn-danger">Delete Post</a>

    

{% endblock content %}

templates/pages/post_new.html
{% extends "base.html" %}

{% block content %}

    <h1>New Post</h1>
    <form action = "" method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value = "Save" class="btn btn-success">
    </form>

{% endblock content %}

templates/pages/post_search.html
{% extends "base.html" %}

{% block content %}
    {% for post in all_search_results %}
        <h3>{{post.title}}</h3>
        <img src="{{ post.image.url }}">
        <p>{{post.text}}</p>
        <small>{{ post.author }}</small>
    {% empty %}
        <h2>No results found</h2>
    {% endfor %}
{% endblock %}

templates/pages/wel.html
{% extends "base.html" %}

{% block content %}

<h1> Welcome!</h1>

{% endblock content %}